---
name: CI
# yamllint disable-line rule:truthy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install python dependencies
        run: pip3 install ruff
      - name: Run ruff check
        run: ruff check
      - name: Run ruff format
        run: ruff format --check

  srpm:
    runs-on: ubuntu-latest
    needs:
      - ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create SRPM
        run: |
          git archive --format=tar.gz --prefix=radiusd-otp-0.1.0/ \
              -o ../radiusd-otp-0.1.0.tar.gz HEAD
          rpmbuild -bs \
              --define "_sourcedir $(pwd)/.." \
              --define "_srcrpmdir $(pwd)/dist" \
              rpm/radiusd-otp.spec
      - name: Store SRPM to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: source-rpm
          path: dist/*.src.rpm
          retention-days: 7

  rpm:
    runs-on: ubuntu-latest
    needs:
      - srpm
    strategy:
      matrix:
        dist: [el9, el10]
        include:
          - dist: el9
            mock_config: rocky+epel-9-x86_64
          - dist: el10
            mock_config: rocky+epel-10-x86_64
    timeout-minutes: 5
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install build tools
        run: |
          dnf -y install \
              git \
              mock \
              pyproject-rpm-macros \
              python3-devel \
              rpm-build
      - name: Create SRPM
        run: |
          pwd
          ls -al
          git archive --format=tar.gz --prefix=radiusd-otp-0.1.0/ \
              -o ../radiusd-otp-0.1.0.tar.gz HEAD
          rpmbuild -bs \
              --define "_sourcedir $(pwd)/.." \
              --define "_srcrpmdir $(pwd)/dist" \
              rpm/radiusd-otp.spec
      - name: Build RPM
        run: |
          mock -r ${{ matrix.mock_config }} \
              --rebuild dist/*.src.rpm \
              --resultdir=artifacts
      - name: Upload RPM to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: rpm-${{ matrix.dist }}
          path: artifacts/*.rpm
          retention-days: 7

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: mock-logs-${{ matrix.dist }}
          path: artifacts/*.log
